name: Shield
version: 0.3
author: firecopy
main: com.gmail.firecopy1.shield.Shield
description: Make a Shield and get ready for battle!
permissions:
  shield.use:
    description: Toggles if a player can use a shield.
    default: true
